// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phdixypytjgwcelamfdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoZGl4eXB5dGpnd2NlbGFtZmRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDUyNjgsImV4cCI6MjA1OTc4MTI2OH0.fx5eWF41Vg6j3zXE99rX7HQdBuPbaV67uKXbuynoJws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);